
# This file was generated by 'versioneer.py' (0.27) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-07T10:04:30+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "c4f12e915842b03ad720f8480f2c901b5fd91cae",
 "version": "0.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
